name: Bug
description: Report a bug to improve Lyli's frontend.
title: '[Bug] '
labels: ['bug']
assignees:
  - 'RappyTV'
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you encountered.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Give us additional information that could help us reproduce the bug. You can also attach screenshots or videos.